import JSZip from "jszip";

/**
 * Normalizes template data into standard Elementor export format compatible with both Elementor Free & Pro.
 */
function formatElementorExport(data, defaultType, title) {
  let contentArray = [];
  
  if (data && typeof data === "object" && !Array.isArray(data)) {
    if (Array.isArray(data.content)) {
      contentArray = data.content;
    } else {
      contentArray = [data];
    }
  } else if (Array.isArray(data)) {
    contentArray = data;
  }

  // Use "section" for headers/footers so Elementor Free & Pro can BOTH import without "Invalid template type" error
  const safeType = (defaultType === "header" || defaultType === "footer") ? "section" : defaultType;

  return {
    version: "0.4",
    title: title,
    type: safeType,
    page_settings: {
      page_template: "elementor_canvas",
    },
    content: contentArray,
  };
}

/**
 * Packages Elementor templates and WordPress theme skeleton into a downloadable ZIP archive.
 * @param {Object} params
 * @param {Array|Object} params.header - Header template JSON
 * @param {Array|Object} params.footer - Footer template JSON
 * @param {Array|Object} params.content - Content template JSON
 * @param {Object} [params.globalClasses] - Global styles / classes
 * @param {Object} [params.siteMeta] - Site metadata (title, summary)
 * @returns {Promise<Buffer>} Node.js Buffer containing the generated ZIP file
 */
export async function buildThemeZip({ header, footer, content, globalClasses, siteMeta }) {
  const zip = new JSZip();

  const themeTitle = (siteMeta && siteMeta.title) ? siteMeta.title : "AI Converter Elementor Theme";

  // Convert global classes into CSS rules for style.css
  let globalCss = "";
  if (globalClasses && typeof globalClasses === "object") {
    for (const [className, styles] of Object.entries(globalClasses)) {
      if (styles && typeof styles === "object") {
        const cssProps = Object.entries(styles)
          .map(([k, v]) => `  ${k.replace(/_/g, "-")}: ${v};`)
          .join("\n");
        globalCss += `.${className} {\n${cssProps}\n}\n\n`;
      }
    }
  }

  const styleCssContent = `/*
Theme Name: ${themeTitle}
Theme URI: https://aiconverter.ai
Author: AI Converter
Description: Elementor-ready full-width custom theme package generated by AI Converter.
Version: 1.0.0
Text Domain: aiconverter-theme
*/

/* Full-Width Edge-to-Edge Reset - Strips default theme margins and header wrappers */
html, body {
  margin: 0 !important;
  padding: 0 !important;
  width: 100% !important;
  max-width: 100% !important;
  overflow-x: hidden;
}

.site-header,
.site-branding,
.entry-header,
.page-header,
.header-wrapper,
#masthead,
#site-header {
  display: none !important;
}

.elementor-section-full_width,
.elementor-container,
.e-con-full {
  max-width: 100% !important;
}

${globalCss}
`;

  const functionsPhpContent = `<?php
/**
 * AI Converter Theme Functions & Elementor Full-Width Canvas Support
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

function aiconverter_theme_setup() {
	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'elementor' );
}
add_action( 'after_setup_theme', 'aiconverter_theme_setup' );
`;

  const headerPhpContent = `<?php
/**
 * AI Converter Theme Clean Full-Width Header
 * Strips out default WordPress theme title/tagline header wrappers.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
`;

  const footerPhpContent = `<?php
/**
 * AI Converter Theme Clean Full-Width Footer
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
wp_footer();
?>
</body>
</html>
`;

  const indexPhpContent = `<?php
/**
 * AI Converter Theme Main Template File
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
get_header();
if ( have_posts() ) {
	while ( have_posts() ) {
		the_post();
		the_content();
	}
}
get_footer();
`;

  // Standard Elementor Template Objects (Compatible with Elementor Free & Pro)
  const headerExport = formatElementorExport(header, "section", `${themeTitle} - Header`);
  const footerExport = formatElementorExport(footer, "section", `${themeTitle} - Footer`);
  const contentExport = formatElementorExport(content, "page", `${themeTitle} - Main Content`);
  
  // Format global-classes as a valid Elementor import object
  const globalClassesExport = {
    version: "0.4",
    title: `${themeTitle} - Global Styles`,
    type: "section",
    page_settings: {
      page_template: "elementor_canvas",
      custom_css: globalCss,
    },
    content: [],
    global_classes: globalClasses || {},
  };

  // 1. Root Level Theme Files (Required for WordPress Theme Installer)
  zip.file("style.css", styleCssContent);
  zip.file("functions.php", functionsPhpContent);
  zip.file("header.php", headerPhpContent);
  zip.file("footer.php", footerPhpContent);
  zip.file("index.php", indexPhpContent);
  zip.file("page.php", indexPhpContent);
  zip.file("single.php", indexPhpContent);

  // 2. Elementor JSON Folder (Ready for Elementor -> Import Templates)
  const jsonFolder = zip.folder("elementor-json");
  jsonFolder.file("header-template.json", JSON.stringify(headerExport, null, 2));
  jsonFolder.file("footer-template.json", JSON.stringify(footerExport, null, 2));
  jsonFolder.file("content-template.json", JSON.stringify(contentExport, null, 2));
  jsonFolder.file("global-classes.json", JSON.stringify(globalClassesExport, null, 2));

  // 3. Theme Skeleton Subfolder
  const themeFolder = zip.folder("theme");
  themeFolder.file("style.css", styleCssContent);
  themeFolder.file("functions.php", functionsPhpContent);
  themeFolder.file("header.php", headerPhpContent);
  themeFolder.file("footer.php", footerPhpContent);
  themeFolder.file("index.php", indexPhpContent);
  themeFolder.file("page.php", indexPhpContent);
  themeFolder.file("single.php", indexPhpContent);

  // 4. README Instructions
  zip.file("README.txt", `AI CONVERTER ELEMENTOR THEME PACKAGE
====================================

Theme Title: ${themeTitle}
Generated By: AI Converter

OPTION 1: INSTALL AS WORDPRESS THEME (RECOMMENDED - 100% FULL-WIDTH)
1. Go to WordPress Admin > Appearance > Themes > Add New > Upload Theme.
2. Choose and upload this .zip file directly. WordPress will install and activate the theme.
3. Your page will render 100% full-width with NO default theme headers!

OPTION 2: IMPORT TEMPLATES INTO ELEMENTOR
1. Go to WordPress Admin > Templates > Saved Templates (or Templates > Import Templates).
2. Click "Import Templates" at the top right.
3. Unzip this package and import each JSON file from the 'elementor-json' folder:
   - header-template.json  (Header Template)
   - content-template.json (Main Content Template)
   - footer-template.json  (Footer Template)
   - global-classes.json   (Global Styles & CSS)
`);

  const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });
  return zipBuffer;
}
